name: build
on:
  push:
    branches: [main]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout build library in builder branch
        uses: actions/checkout@v4
        with:
          ref: builder
          path: '.'
      - name: delete old pages
        run: rm -rf _pages
      - name: checkout build library in main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: './_pages'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm i
      - run: node index pages
      - run: date +%s > report.txt
      - name: Update Repo
        run: |
          git config --global user.name "tezyns"
          git config --global user.email "tezyns@outlook.com"
          git add .
          git commit -m "deployment"
          git push
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './_site'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        